# Generated by Django 5.1.2 on 2024-11-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(default=None, max_length=250)),
                ('cart_proid', models.IntegerField(null=True)),
                ('cart_name', models.CharField(max_length=250)),
                ('cart_price', models.FloatField(max_length=250)),
                ('cart_image', models.FileField(null=True, upload_to='')),
                ('cart_qty', models.IntegerField()),
                ('cart_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_price', models.IntegerField(null=True)),
                ('cat_image', models.FileField(null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prouser', models.CharField(default=None, max_length=250)),
                ('order_proname', models.CharField(max_length=250)),
                ('order_proprice', models.FloatField(max_length=250)),
                ('order_proimage', models.FileField(null=True, upload_to='')),
                ('order_proqty', models.IntegerField()),
                ('order_proamount', models.FloatField()),
                ('order_address', models.TextField(null=True)),
                ('order_paytype', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('area', models.CharField(max_length=250, null=True)),
                ('town', models.CharField(max_length=250, null=True)),
                ('district', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
                ('mobile', models.IntegerField(default=None, null=True)),
                ('order_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_cname', models.CharField(max_length=255)),
                ('reg_cemail', models.TextField(max_length=255, unique=True)),
                ('reg_cphone', models.CharField(max_length=255)),
                ('reg_username', models.CharField(max_length=255)),
                ('reg_psw', models.CharField(max_length=2)),
                ('reg_date', models.DateField(null=True)),
                ('reg_gender', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savedaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Savedaddress_name', models.CharField(max_length=250)),
                ('Savedaddress_mobile', models.IntegerField(null=True)),
                ('Savedaddress_pincode', models.IntegerField(null=True)),
                ('Savedaddress_state', models.CharField(max_length=100)),
                ('Savedaddress_town', models.CharField(max_length=100)),
                ('Savedaddress_district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_user', models.CharField(default=None, max_length=250)),
                ('wishlist_proid', models.IntegerField(null=True)),
                ('wishlist_name', models.CharField(max_length=250)),
                ('wishlist_price', models.FloatField(max_length=250)),
                ('wishlist_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=250)),
                ('pro_price', models.FloatField()),
                ('pro_image', models.FileField(null=True, upload_to='products')),
                ('pro_cats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
