# Generated by Django 5.1.2 on 2024-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_order_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
