# Generated by Django 5.1.2 on 2024-11-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_order_areas_remove_order_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
    ]
