# Generated by Django 5.1.2 on 2024-11-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_area_order_district_order_mobile_order_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savedaddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town',
        ),
        migrations.RemoveField(
            model_name='register',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='reg_gender',
        ),
    ]
