# Generated by Django 5.1.2 on 2024-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order_district_order_mobile_order_name_order_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='areas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
